# 100 numpy exercises (Optional)

Source: https://github.com/rougier/numpy-100


#### How to run this notebook

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

#### How to get help

If you are stuck, you can ask for help on the community forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561 . You can get help with errors, ask for hints, and share your solutions with others.

If you're new to Numpy, check out this notebook for a quick tutorial: https://jovian.ml/aakashns/python-numerical-computing-with-numpy


#### Saving your work

Remember to save a snapshot of your work from time to time using to your Jovian.ml account.

In [24]:
# !pip install jovian --upgrade --quiet

In [25]:
import jovian

In [28]:
jovian.commit(project='100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/100-numpy-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/100-numpy-exercises


'https://jovian.ml/aakashns/100-numpy-exercises'

`jovian.commit` uploads the notebook to your Jovian.ml account, captures the Python environment and creates a shareable link for your notebook as shown above. You can use this link to share your work and let anyone (including you) run your notebooks and reproduce your work. Learn more: https://jovian.ml/docs/


In [ ]:
# Ucomment the next line if you need install numpy
# !pip install numpy --upgrade

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

2.2.1
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30157",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30157",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-gf60t9tw/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib 

c:\Users\chris\Portofolio\Course\Data-Analysis-with-Python-by-Jovian\.venv\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
memory_size = null_vector.nbytes
print(f"Memory size of the array: {memory_size} bytes")

Memory size of the array: 80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [15]:
# You can use the following methods in Pythons interactive shell:
# 1. `help(numpy.add)` - Displays detailed documentation
# 2. `numpy.add.__doc__` - Shows the docstring
# 3. `print(numpy.info(numpy.add))` - Prints function information

# Alternative using IPython:
# - Use `?numpy.add` or `??numpy.add` for basic or detailed help
# - Use `%help numpy.add` for IPythons help system

# Note: Make sure to import numpy first using `import numpy` 

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [16]:
null_vector_with_one = np.zeros(10)
null_vector_with_one[4] = 1
print(null_vector_with_one)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [17]:
vector_10_to_49 = np.arange(10, 50)
print(vector_10_to_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [18]:
reversed_vector = vector_10_to_49[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [19]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [21]:
# A non-zero element in an array is any element that is not equal to zero. In the context of the provided code, the 

# The np.nonzero function returns a tuple of arrays, each containing the indices of the non-zero elements in the input array. In this case, it will return the indices of the elements 1, 2, and 4, which are at positions 0, 1, and 4 respectively.
array = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(array)
print(non_zero_indices)

(array([0, 1, 4]),)


Save your progress by commiting your work to Jovian

In [4]:
import jovian

<IPython.core.display.Javascript object>

In [27]:
jovian.commit(project='numpy-100-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 11. Create a 3x3 identity matrix (★☆☆)

In [22]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [23]:
random_3x3x3_array = np.random.random((3, 3, 3))
print(random_3x3x3_array)

[[[0.07962889 0.45390379 0.19993879]
  [0.9797109  0.78149956 0.8184778 ]
  [0.41643747 0.17349432 0.88358449]]

 [[0.51439548 0.24206136 0.37999947]
  [0.8773817  0.91553853 0.5698833 ]
  [0.05313742 0.88468978 0.43155208]]

 [[0.77626197 0.71691756 0.98438682]
  [0.72910335 0.42514799 0.36522376]
  [0.87766247 0.55478823 0.88913399]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [24]:
random_10x10_array = np.random.random((10, 10))
min_value = random_10x10_array.min()
max_value = random_10x10_array.max()
print("Random 10x10 array:\n", random_10x10_array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Random 10x10 array:
 [[0.09014106 0.0282667  0.96428967 0.45721199 0.39045966 0.41922425
  0.40772543 0.98773885 0.25645693 0.13083051]
 [0.44406309 0.29534263 0.2167273  0.20747692 0.54066004 0.87887511
  0.193235   0.38403283 0.97383346 0.19833655]
 [0.87191662 0.54532794 0.24666299 0.40845643 0.82737499 0.7777214
  0.18251832 0.67453424 0.07099332 0.7797825 ]
 [0.33254086 0.63669439 0.88656483 0.53472006 0.50421253 0.43060782
  0.92318212 0.46102954 0.77575533 0.14629618]
 [0.24161342 0.09807972 0.71040745 0.14069246 0.66109865 0.31794487
  0.2711011  0.74973418 0.10701666 0.1634898 ]
 [0.13602361 0.05270729 0.2693508  0.33261473 0.26388578 0.62462663
  0.7586921  0.49004818 0.06017178 0.74963597]
 [0.35212847 0.65024363 0.72539603 0.13491111 0.8570242  0.21786975
  0.22370254 0.88244501 0.86472431 0.4094618 ]
 [0.71595889 0.47519689 0.23170193 0.81630818 0.76439529 0.05672482
  0.47893911 0.87252441 0.4617118  0.00361506]
 [0.09535104 0.65952003 0.81898111 0.15635932 0.59333924 0.3

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [25]:
random_vector = np.random.random(30)
mean_value = random_vector.mean()
print("Random vector:", random_vector)
print("Mean value:", mean_value)

Random vector: [0.7920801  0.12213534 0.5194166  0.56470574 0.3955325  0.90588674
 0.75449755 0.93143889 0.99077496 0.23560347 0.1251017  0.30962601
 0.13552396 0.04208607 0.67647648 0.93884198 0.00743207 0.85972307
 0.35521555 0.17853259 0.99448439 0.16368155 0.90768491 0.17575086
 0.54484236 0.12720116 0.59432956 0.97972619 0.69892278 0.09846266]
Mean value: 0.5041905926076061


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [26]:
array_2d = np.ones((5, 5))
array_2d[1:-1, 1:-1] = 0
print(array_2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [27]:
bordered_array = np.pad(array_2d, pad_width=1, mode='constant', constant_values=0)
print(bordered_array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [28]:
# 0 multiplied by np.nan results in np.nan
result_1 = 0 * np.nan  # Output: nan

# np.nan is not equal to np.nan
result_2 = np.nan == np.nan  # Output: False

# np.inf is not greater than np.nan
result_3 = np.inf > np.nan  # Output: False

# np.nan minus np.nan results in np.nan
result_4 = np.nan - np.nan  # Output: nan

# np.nan is considered in a set containing np.nan
result_5 = np.nan in set([np.nan])  # Output: True

# 0.3 is not exactly equal to 3 times 0.1 due to floating-point precision issues
result_6 = 0.3 == 3 * 0.1  # Output: False

# Print the results
print(result_1)
print(result_2)
print(result_3)
print(result_4)
print(result_5)
print(result_6)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [29]:
matrix_with_diag = np.diag([1, 2, 3, 4], k=-1)
print(matrix_with_diag)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [30]:
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [31]:
index_100th_element = np.unravel_index(100, (6, 7, 8))
print(index_100th_element)

(np.int64(1), np.int64(5), np.int64(4))


Save your progress by commiting your work to Jovian

In [7]:
import jovian

In [6]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [32]:
pattern = np.array([[0,1], [1,0]])
checkerboard_tile = np.tile(pattern, (4,4))
print(checkerboard_tile)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [33]:
# Create a 5x5 random matrix
random_matrix = np.random.random((5, 5))

# Normalize the matrix
# Subtract the minimum value from each element
# Divide by the range (maximum value - minimum value)
normalized_matrix = (random_matrix - random_matrix.min()) / (random_matrix.max() - random_matrix.min())

print("Random matrix:\n", random_matrix)
print("Normalized matrix:\n", normalized_matrix)

Random matrix:
 [[0.78080545 0.83870546 0.81434963 0.45260504 0.9320642 ]
 [0.94457936 0.2267516  0.67454864 0.87149177 0.96511036]
 [0.72401843 0.72395031 0.75666569 0.20902953 0.50277613]
 [0.74268546 0.9906677  0.38597834 0.77136607 0.02676395]
 [0.16051296 0.74855481 0.14801104 0.29537991 0.60854951]]
Normalized matrix:
 [[0.78227884 0.84234708 0.81707918 0.44178798 0.93920192]
 [0.95218575 0.20747678 0.67204292 0.87636117 0.9734856 ]
 [0.72336525 0.72329458 0.75723509 0.18909105 0.49383788]
 [0.74273133 1.         0.37266624 0.77248597 0.        ]
 [0.13875764 0.74882048 0.12578755 0.27867508 0.60357226]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [34]:
# Create a custom dtype for RGBA color
# Each component (Red, Green, Blue, Alpha) is represented as an unsigned byte (uint8)
# uint8 ranges from 0 to 255, perfect for color components
color_dtype = np.dtype([('R', np.uint8), 
                       ('G', np.uint8),
                       ('B', np.uint8), 
                       ('A', np.uint8)])

# Create a color array using the custom dtype
# Create one color as example: red with 50% transparency
color = np.array((255, 0, 0, 128), dtype=color_dtype)
print(color)

(255, 0, 0, 128)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [35]:
# Create a 5x3 matrix with random values
matrix_5x3 = np.random.random((5, 3))

# Create a 3x2 matrix with random values
matrix_3x2 = np.random.random((3, 2))

# Perform matrix multiplication (dot product)
# The result will be a 5x2 matrix
result_matrix = np.dot(matrix_5x3, matrix_3x2)

print("5x3 matrix:\n", matrix_5x3)
print("3x2 matrix:\n", matrix_3x2)
print("Result of multiplication (5x2 matrix):\n", result_matrix)

5x3 matrix:
 [[0.50735487 0.64930988 0.17377111]
 [0.46117249 0.75036188 0.11096941]
 [0.39000378 0.01949046 0.97995703]
 [0.01489791 0.77654789 0.95690973]
 [0.735702   0.78411492 0.20869803]]
3x2 matrix:
 [[0.72534102 0.88259177]
 [0.0895083  0.43867142]
 [0.6945347  0.53551982]]
Result of multiplication (5x2 matrix):
 [[0.54681399 0.82567879]
 [0.47874305 0.79561567]
 [0.96524446 0.87755045]
 [0.74492056 0.86624227]
 [0.74876765 1.10505526]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [36]:
# Create a sample 1D array
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Negate elements between 3 and 8 (inclusive)
# Using boolean masking to identify elements between 3 and 8
# The & operator performs element-wise AND operation
# Z[condition] selects elements where condition is True
Z[(Z >= 3) & (Z <= 8)] *= -1

print(Z)

[ 1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [37]:
# The first print statement uses Python's built-in sum function.
# sum(range(5), -1) calculates the sum of the range(5) which is [0, 1, 2, 3, 4] and adds -1 to it.
# So, sum([0, 1, 2, 3, 4]) = 10, and 10 + (-1) = 9.
print(sum(range(5), -1))  # Output: 9

# The second print statement uses numpy's sum function.
# When using numpy's sum function, the second argument is interpreted as the axis along which to sum.
# Since range(5) produces a 1D array [0, 1, 2, 3, 4], specifying axis=-1 sums along the last axis.
# Therefore, it sums all elements in the array [0, 1, 2, 3, 4], resulting in 10.
from numpy import *
print(sum(range(5), -1))  # Output: 10

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [38]:
# Let's analyze each expression:

# 1. Z**Z 
# Legal: Element-wise exponentiation where each element is raised to power of itself
# Example: if Z = [2,3], result = [4,27]

# 2. 2 << Z >> 2
# Legal: Bitwise shift operations 
# First shifts 2 left by Z positions, then shifts result right by 2
# Note: Be careful with large values as shifts can overflow

# 3. Z <- Z
# Illegal in Python: '<-' is not a valid operator in Python
# This is valid in R but not in Python. Use '=' or '==' instead

# 4. 1j*Z
# Legal: Multiplies Z by complex number 1j
# Converts integer vector to complex vector
# Example: if Z = [1,2], result = [1j,2j]

# 5. Z/1/1
# Legal: Double division
# Equivalent to (Z/1)/1, which is same as Z
# Note: Division converts integers to floating point

# 6. Z<Z>Z
# Illegal: Invalid syntax
# Cannot chain comparison operators this way
# Should be written as (Z<Z) or (Z>Z) separately

Z = np.array([2, 3])

print("Z**Z:", Z**Z)  # [4 27]
print("2 << Z >> 2:", 2 << Z >> 2)  # [2 8]
print("1j*Z:", 1j*Z)  # [2.j 3.j]
print("Z/1/1:", Z/1/1)  # [2. 3.]

Z**Z: [ 4 27]
2 << Z >> 2: [2 4]
1j*Z: [0.+2.j 0.+3.j]
Z/1/1: [2. 3.]


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [40]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\chris\AppData\Local\Temp\ipykernel_6340\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\chris\AppData\Local\Temp\ipykernel_6340\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\chris\AppData\Local\Temp\ipykernel_6340\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [41]:
float_array = np.array([-2.7, -1.5, -0.2, 0.2, 1.5, 2.7])
rounded_array = np.copysign(np.ceil(np.abs(float_array)), float_array)
print(rounded_array)

[-3. -2. -1.  1.  2.  3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [42]:
# Create two test arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 5, 6, 7, 8])

# Find common values between the two arrays
common_values = np.intersect1d(arr1, arr2)

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Common values:", common_values)

Array 1: [1 2 3 4 5]
Array 2: [4 5 6 7 8]
Common values: [4 5]


Save your progress by commiting your work to Jovian

In [8]:
import jovian

In [9]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [43]:
# Ignore all numpy warnings
np.seterr(all='ignore')

# Example code that would normally generate warnings
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [44]:
# Let's break down the expressions to understand if they are true.

# np.sqrt(-1):

# np.sqrt is a function from the NumPy library that computes the square root of a number.
# When you pass a negative number to np.sqrt, it returns nan (Not a Number) because the square root of a negative number is not defined in the set of real numbers.
# np.emath.sqrt(-1):

# np.emath.sqrt is a function from the NumPy library that computes the square root of a number, but it is part of the emath module which handles complex numbers.
# When you pass a negative number to np.emath.sqrt, it returns a complex number. In this case, np.emath.sqrt(-1) returns 1j, which is the imaginary unit.


result = np.sqrt(-1) == np.emath.sqrt(-1)
print(result)

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [46]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2025-01-03
Today: 2025-01-04
Tomorrow: 2025-01-05


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [47]:
july_2016 = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(july_2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [48]:
# Create sample arrays A and B
A = np.ones(3)
B = np.ones(3)

# Compute ((A+B)*(-A/2)) in place without creating temporary arrays
# 1. First compute A/2 and store in A itself
A /= 2.0
# 2. Negate A in place
A *= -1
# 3. Add B to A and multiply the result with original A
A *= (A + B)

print(A)

# The above computation breaks down the formula ((A+B)*(-A/2)) into steps:
# 1. A = A/2 
# 2. A = -A
# 3. A = A * (A + B)
# Each step modifies A in place without creating new arrays
# This saves memory as we reuse the same array instead of creating temporary ones

[-0.25 -0.25 -0.25]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [52]:
# Create a random array of positive numbers
random_array = np.random.random(10) * 100
print("Original array:", random_array)

# Method 1: Using np.floor
integer_part_floor = np.floor(random_array)
print("Integer part using np.floor:", integer_part_floor)

# Method 2: Using np.trunc
integer_part_trunc = np.trunc(random_array)
print("Integer part using np.trunc:", integer_part_trunc)

# Method 3: Using astype(int)
integer_part_astype = random_array.astype(int)
print("Integer part using astype(int):", integer_part_astype)

# Method 4: Using np.floor_divide
integer_part_floor_divide = np.floor_divide(random_array, 1)
print("Integer part using np.floor_divide:", integer_part_floor_divide)


Original array: [50.17167894 53.92595714 42.72495773 48.22982292 81.02331564 70.09155866
 61.74884683 91.68134541 73.65955191 79.81699573]
Integer part using np.floor: [50. 53. 42. 48. 81. 70. 61. 91. 73. 79.]
Integer part using np.trunc: [50. 53. 42. 48. 81. 70. 61. 91. 73. 79.]
Integer part using astype(int): [50 53 42 48 81 70 61 91 73 79]
Integer part using np.floor_divide: [50. 53. 42. 48. 81. 70. 61. 91. 73. 79.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [50]:
# Create a 5x5 matrix where each row contains values from 0 to 4
# Method 1: Using np.tile and np.arange
# 1. Create array [0,1,2,3,4] using np.arange
# 2. Create 5 copies of this array using np.tile 
# 3. Reshape into 5x5 matrix
matrix = np.tile(np.arange(5), 5).reshape(5, 5)

# Method 2: Using broadcasting with mgrid
# This creates a matrix where each row is [0,1,2,3,4]
matrix = np.zeros((5, 5)) + np.arange(5)

print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [51]:
def generate_integers():
    for i in range(10):
        yield i

# Use the generator to build an array
generated_array = np.fromiter(generate_integers(), dtype=int)
print(generated_array)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [53]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
# We can use the linspace function to generate evenly spaced values within a specified range
# However, linspace includes the endpoints by default, so we need to exclude them
# We can achieve this by specifying the start and stop parameters slightly inside the desired range

vector_0_to_1_excluded = np.linspace(0, 1, 12)[1:-1]
print(vector_0_to_1_excluded)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [54]:
# Create a random vector of size 10
random_vector = np.random.random(10)
print("Original random vector:", random_vector)

# Sort the vector
sorted_vector = np.sort(random_vector)
print("Sorted vector:", sorted_vector)

Original random vector: [0.52184988 0.65267868 0.0457879  0.50065808 0.48236715 0.36282085
 0.00175523 0.25255608 0.79525598 0.96855907]
Sorted vector: [0.00175523 0.0457879  0.25255608 0.36282085 0.48236715 0.50065808
 0.52184988 0.65267868 0.79525598 0.96855907]


Save your progress by commiting your work to Jovian

In [45]:
import jovian

ModuleNotFoundError: No module named 'jovian'

In [11]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [55]:
# Create a small array for testing
small_array = np.array([1, 2, 3, 4])

# Method 1: Using np.sum
# This is the standard way but may have overhead for small arrays
sum1 = np.sum(small_array)

# Method 2: Using Python's built-in sum
# This can be faster for very small arrays
sum2 = sum(small_array)

# Method 3: Using array.sum()
# This is a method of the array object
sum3 = small_array.sum()

# Method 4: Using reduce and add
# This can be faster for small arrays
sum4 = np.add.reduce(small_array)

print("Results:")
print("np.sum():", sum1)
print("built-in sum():", sum2)
print("array.sum():", sum3)
print("np.add.reduce():", sum4)

# Note: For very small arrays, Python's built-in sum() might be faster
# because numpy's sum has some overhead for setting up the calculation

Results:
np.sum(): 10
built-in sum(): 10
array.sum(): 10
np.add.reduce(): 10


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [56]:
are_equal = np.array_equal(A, B)
print("Are arrays A and B equal?", are_equal)

Are arrays A and B equal? False


#### 43. Make an array immutable (read-only) (★★☆)

In [57]:
# Create a sample array
immutable_array = np.array([1, 2, 3, 4, 5])

# Make the array immutable (read-only)
immutable_array.flags.writeable = False

print(immutable_array)

# Trying to modify the array will now raise an error
# immutable_array[0] = 10  # Uncommenting this line will raise a ValueError

[1 2 3 4 5]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [58]:
# Create a random 10x2 matrix representing Cartesian coordinates
cartesian_coords = np.random.random((10, 2))
print("Cartesian coordinates:\n", cartesian_coords)

# Convert to polar coordinates
# Radius r is calculated as the Euclidean distance from the origin
r = np.sqrt(cartesian_coords[:, 0]**2 + cartesian_coords[:, 1]**2)

# Angle theta is calculated using the arctan2 function
theta = np.arctan2(cartesian_coords[:, 1], cartesian_coords[:, 0])

# Combine r and theta into a single array
polar_coords = np.column_stack((r, theta))
print("Polar coordinates:\n", polar_coords)

Cartesian coordinates:
 [[0.89937124 0.03188155]
 [0.26624015 0.11797186]
 [0.85753592 0.63471683]
 [0.74021786 0.68049063]
 [0.34482378 0.09082762]
 [0.57506482 0.4851021 ]
 [0.31128173 0.34462879]
 [0.01149208 0.00620273]
 [0.36009199 0.87001635]
 [0.38794276 0.09053662]]
Polar coordinates:
 [[0.89993614 0.03543387]
 [0.29120642 0.41710375]
 [1.06688018 0.63717599]
 [1.00547998 0.74338245]
 [0.35658533 0.25755294]
 [0.7523454  0.70074384]
 [0.4643978  0.8361953 ]
 [0.01305916 0.49493163]
 [0.94159157 1.17837255]
 [0.39836725 0.22927261]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [59]:
# Create a random vector of size 10
random_vector = np.random.random(10)
print("Original random vector:", random_vector)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Modified vector with maximum value replaced by 0:", random_vector)

Original random vector: [0.31322507 0.35756986 0.82429182 0.00801343 0.74149814 0.46253861
 0.32501379 0.74263528 0.24802952 0.74086468]
Modified vector with maximum value replaced by 0: [0.31322507 0.35756986 0.         0.00801343 0.74149814 0.46253861
 0.32501379 0.74263528 0.24802952 0.74086468]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [60]:
# Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

# Define the structured data type with fields 'x' and 'y', both of type float
dtype = np.dtype([('x', np.float64), ('y', np.float64)])

# Generate a grid of coordinates using np.mgrid
# np.mgrid[0:1:5j, 0:1:5j] generates a 5x5 grid of coordinates from 0 to 1
# The 'j' indicates that the range should be divided into 5 equal intervals
x, y = np.mgrid[0:1:5j, 0:1:5j]

# Combine the x and y coordinates into a structured array
# Use np.zeros to create an empty array with the desired shape and dtype
# Assign the x and y coordinates to the respective fields
structured_array = np.zeros(x.shape, dtype=dtype)
structured_array['x'], structured_array['y'] = x, y

print(structured_array)

[[(0.  , 0.  ) (0.  , 0.25) (0.  , 0.5 ) (0.  , 0.75) (0.  , 1.  )]
 [(0.25, 0.  ) (0.25, 0.25) (0.25, 0.5 ) (0.25, 0.75) (0.25, 1.  )]
 [(0.5 , 0.  ) (0.5 , 0.25) (0.5 , 0.5 ) (0.5 , 0.75) (0.5 , 1.  )]
 [(0.75, 0.  ) (0.75, 0.25) (0.75, 0.5 ) (0.75, 0.75) (0.75, 1.  )]
 [(1.  , 0.  ) (1.  , 0.25) (1.  , 0.5 ) (1.  , 0.75) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [61]:
# Given two arrays X and Y
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Construct the Cauchy matrix C
C = 1.0 / (X[:, np.newaxis] - Y[np.newaxis, :])
print(C)

[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [62]:
# List of numpy scalar types
scalar_types = [np.int8, np.int16, np.int32, np.int64, 
                np.uint8, np.uint16, np.uint32, np.uint64, 
                np.float16, np.float32, np.float64]

# Print the minimum and maximum representable values for each type
for dtype in scalar_types:
    if np.issubdtype(dtype, np.integer):
        info = np.iinfo(dtype)
    else:
        info = np.finfo(dtype)
    print(f"{dtype.__name__}: min={info.min}, max={info.max}")

int8: min=-128, max=127
int16: min=-32768, max=32767
int32: min=-2147483648, max=2147483647
int64: min=-9223372036854775808, max=9223372036854775807
uint8: min=0, max=255
uint16: min=0, max=65535
uint32: min=0, max=4294967295
uint64: min=0, max=18446744073709551615
float16: min=-65504.0, max=65504.0
float32: min=-3.4028234663852886e+38, max=3.4028234663852886e+38
float64: min=-1.7976931348623157e+308, max=1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [63]:
# Create a sample array
sample_array = np.arange(10000).reshape(100, 100)

# Set print options to print all values
np.set_printoptions(threshold=np.inf)

# Print the array
print(sample_array)

[[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
    14   15   16   17   18   19   20   21   22   23   24   25   26   27
    28   29   30   31   32   33   34   35   36   37   38   39   40   41
    42   43   44   45   46   47   48   49   50   51   52   53   54   55
    56   57   58   59   60   61   62   63   64   65   66   67   68   69
    70   71   72   73   74   75   76   77   78   79   80   81   82   83
    84   85   86   87   88   89   90   91   92   93   94   95   96   97
    98   99]
 [ 100  101  102  103  104  105  106  107  108  109  110  111  112  113
   114  115  116  117  118  119  120  121  122  123  124  125  126  127
   128  129  130  131  132  133  134  135  136  137  138  139  140  141
   142  143  144  145  146  147  148  149  150  151  152  153  154  155
   156  157  158  159  160  161  162  163  164  165  166  167  168  169
   170  171  172  173  174  175  176  177  178  179  180  181  182  183
   184  185  186  187  188  189  190  191  192  193

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [64]:
# Given vector and scalar
vector = np.array([1, 3, 8, 10, 15])
scalar = 9

# Find the index of the closest value
index = np.abs(vector - scalar).argmin()

# Get the closest value
closest_value = vector[index]

print("Vector:", vector)
print("Scalar:", scalar)
print("Closest value:", closest_value)

Vector: [ 1  3  8 10 15]
Scalar: 9
Closest value: 8


Save and commit your work.

In [12]:
import jovian

In [13]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [3]:
# Define the structured data type with fields 'x', 'y', 'r', 'g', 'b'
dtype = np.dtype([('x', np.float64), ('y', np.float64), 
                  ('r', np.uint8), ('g', np.uint8), ('b', np.uint8)])

# Create a structured array with sample data
structured_array = np.array([(0.0, 0.0, 255, 0, 0), 
                             (1.0, 1.0, 0, 255, 0), 
                             (2.0, 2.0, 0, 0, 255)], dtype=dtype)

print(structured_array)

[(0., 0., 255,   0,   0) (1., 1.,   0, 255,   0) (2., 2.,   0,   0, 255)]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [5]:
from scipy.spatial import distance

# Create a random vector with shape (100, 2) representing coordinates
random_vector = np.random.random((100, 2))

# Compute the pairwise distances between points
distances = distance.cdist(random_vector, random_vector)

print("Random vector:\n", random_vector)
print("Pairwise distances:\n", distances)

Random vector:
 [[0.18105335 0.72459494]
 [0.91612484 0.43135944]
 [0.33404919 0.82192237]
 [0.25575341 0.16351658]
 [0.83593067 0.56298766]
 [0.42206842 0.87169039]
 [0.12853469 0.94314412]
 [0.00760748 0.96931859]
 [0.65606799 0.86478241]
 [0.28704333 0.05810891]
 [0.37842686 0.1356656 ]
 [0.91467517 0.21645879]
 [0.93956523 0.19764337]
 [0.37460898 0.10148681]
 [0.22275147 0.57257557]
 [0.83247843 0.72765806]
 [0.28530262 0.99135919]
 [0.25789485 0.58533545]
 [0.34939324 0.6182071 ]
 [0.20360125 0.81478362]
 [0.44470468 0.14955195]
 [0.66574232 0.51450009]
 [0.36025186 0.5709317 ]
 [0.41794443 0.96319179]
 [0.24088742 0.2153173 ]
 [0.06055004 0.73529966]
 [0.76474876 0.15646812]
 [0.98423825 0.06808822]
 [0.31425867 0.23754363]
 [0.68285863 0.68418252]
 [0.96767131 0.47281744]
 [0.36267403 0.02713515]
 [0.84123097 0.93795871]
 [0.80722826 0.3599991 ]
 [0.22856283 0.72278925]
 [0.0874346  0.73275145]
 [0.44889277 0.50964911]
 [0.93624415 0.58530886]
 [0.93033675 0.79477106]
 [0.39781

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [6]:
# Create a sample float32 array
float_array = np.random.rand(10).astype(np.float32)
print("Original float array:", float_array)

# Convert the float32 array to int32 in place
float_array = float_array.astype(np.int32, copy=False)
print("Converted integer array:", float_array)

Original float array: [0.9717048  0.5624464  0.31849092 0.85173035 0.45106167 0.6047525
 0.7082824  0.93306357 0.18951476 0.91779405]
Converted integer array: [0 0 0 0 0 0 0 0 0 0]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [7]:
import numpy as np

# Define the file content as a string
file_content = """1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11"""

# Use np.genfromtxt to read the file content
# Specify delimiter as ',' and set missing values to np.nan
data = np.genfromtxt(file_content.splitlines(), delimiter=',', dtype=float)

print(data)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [8]:
# Create a sample numpy array
array = np.array([[1, 2], [3, 4]])

# Use np.ndenumerate to get the equivalent of enumerate for numpy arrays
for index, value in np.ndenumerate(array):
    print(index, value)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [9]:
import numpy as np
from scipy.stats import multivariate_normal

# Define the size of the array
size = 10

# Create a grid of (x, y) coordinates
x, y = np.meshgrid(np.linspace(-1, 1, size), np.linspace(-1, 1, size))

# Stack the coordinates to create a 2D array of shape (size*size, 2)
pos = np.dstack((x, y))

# Define the mean and covariance matrix for the Gaussian distribution
mean = [0, 0]
covariance = [[1, 0], [0, 1]]

# Create the Gaussian distribution
rv = multivariate_normal(mean, covariance)

# Generate the 2D Gaussian-like array
gaussian_array = rv.pdf(pos)

print(gaussian_array)

[[0.05854983 0.07133657 0.08272793 0.09131569 0.09593831 0.09593831
  0.09131569 0.08272793 0.07133657 0.05854983]
 [0.07133657 0.08691581 0.10079493 0.11125819 0.11689034 0.11689034
  0.11125819 0.10079493 0.08691581 0.07133657]
 [0.08272793 0.10079493 0.11689034 0.12902442 0.13555594 0.13555594
  0.12902442 0.11689034 0.10079493 0.08272793]
 [0.09131569 0.11125819 0.12902442 0.1424181  0.14962764 0.14962764
  0.1424181  0.12902442 0.11125819 0.09131569]
 [0.09593831 0.11689034 0.13555594 0.14962764 0.15720215 0.15720215
  0.14962764 0.13555594 0.11689034 0.09593831]
 [0.09593831 0.11689034 0.13555594 0.14962764 0.15720215 0.15720215
  0.14962764 0.13555594 0.11689034 0.09593831]
 [0.09131569 0.11125819 0.12902442 0.1424181  0.14962764 0.14962764
  0.1424181  0.12902442 0.11125819 0.09131569]
 [0.08272793 0.10079493 0.11689034 0.12902442 0.13555594 0.13555594
  0.12902442 0.11689034 0.10079493 0.08272793]
 [0.07133657 0.08691581 0.10079493 0.11125819 0.11689034 0.11689034
  0.11125819

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [10]:
# Define the size of the 2D array
array_size = (5, 5)

# Define the number of elements to place
p = 5

# Create an empty 2D array
array_2d = np.zeros(array_size)

# Randomly choose p unique positions in the array
positions = np.random.choice(array_size[0] * array_size[1], p, replace=False)

# Place the elements (e.g., 1) at the chosen positions
np.put(array_2d, positions, 1)

print(array_2d)

[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [11]:
# Create a sample matrix
matrix = np.random.random((5, 5))
print("Original matrix:\n", matrix)

# Subtract the mean of each row
row_means = matrix.mean(axis=1, keepdims=True)
matrix_centered = matrix - row_means

print("Matrix after subtracting the mean of each row:\n", matrix_centered)

Original matrix:
 [[0.16333361 0.9245705  0.52040343 0.09025776 0.4263138 ]
 [0.62612238 0.19903503 0.32134132 0.08105983 0.49683317]
 [0.19001805 0.5895158  0.25896692 0.50098156 0.35434802]
 [0.6568915  0.1764434  0.10447282 0.41391306 0.64754222]
 [0.26929435 0.92005181 0.18377589 0.8214405  0.10692289]]
Matrix after subtracting the mean of each row:
 [[-0.26164221  0.49959468  0.09542761 -0.33471806  0.00133798]
 [ 0.28124403 -0.14584331 -0.02353703 -0.26381851  0.15195482]
 [-0.18874803  0.21074973 -0.11979915  0.12221549 -0.02441805]
 [ 0.2570389  -0.2234092  -0.29537978  0.01406046  0.24768962]
 [-0.19100274  0.45975472 -0.2765212   0.36114341 -0.35337419]]


#### 59. How to sort an array by the nth column? (★★☆)

In [12]:
# Sort the array by the second column (index 1)
sorted_array = array[array[:, 1].argsort()]

print("Original array:\n", array)
print("Sorted array by the second column:\n", sorted_array)

Original array:
 [[1 2]
 [3 4]]
Sorted array by the second column:
 [[1 2]
 [3 4]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [13]:
# Check if any column in the array has all null (NaN) values
def has_null_columns(array):
    return np.any(np.all(np.isnan(array), axis=0))

# Example usage with the 'data' array
null_columns = has_null_columns(data)
print("Does the array have null columns?", null_columns)

Does the array have null columns? False


Save and commit your work.

In [14]:
import jovian

In [15]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 61. Find the nearest value from a given value in an array (★★☆)

In [17]:
# Given array and value
array = np.array([[1, 2], [3, 4], [5, 6]])
value = 3.5

# Flatten the array to make it 1D
flattened_array = array.flatten()

# Find the index of the nearest value
nearest_index = np.abs(flattened_array - value).argmin()

# Get the nearest value
nearest_value = flattened_array[nearest_index]

print("Array:\n", array)
print("Given value:", value)
print("Nearest value:", nearest_value)

Array:
 [[1 2]
 [3 4]
 [5 6]]
Given value: 3.5
Nearest value: 3


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [18]:
# Define the two arrays
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4], [5], [6]])

# Initialize an empty array to store the result
result = np.empty((3, 3))

# Use np.nditer to iterate over the arrays and compute the sum
with np.nditer([array1, array2, result], flags=['external_loop'], op_flags=[['readonly'], ['readonly'], ['writeonly']]) as it:
    for x, y, z in it:
        z[...] = x + y

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Result of the sum:\n", result)

Array 1:
 [[1 2 3]]
Array 2:
 [[4]
 [5]
 [6]]
Result of the sum:
 [[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


#### 63. Create an array class that has a name attribute (★★☆)

In [19]:
import numpy as np

class NamedArray(np.ndarray):
    def __new__(cls, input_array, name=""):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "")

# Example usage
data = np.array([[1, 2], [3, 4], [5, 6]])
named_array = NamedArray(data, name="MyArray")

print("Array:\n", named_array)
print("Name:", named_array.name)

Array:
 [[1 2]
 [3 4]
 [5 6]]
Name: MyArray


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [20]:
# Given vector
vector = np.array([1, 2, 3, 4, 5])

# Index vector (with possible repeated indices)
index_vector = np.array([0, 1, 1, 3, 4, 4, 4])

# Use np.add.at to add 1 to each element indexed by the index_vector
np.add.at(vector, index_vector, 1)

print("Updated vector:", vector)

Updated vector: [2 4 3 5 8]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [21]:
# Given vector X
X = np.array([1, 2, 3, 4, 5])

# Index list I
I = np.array([0, 1, 2, 1, 0])

# Initialize the array F with zeros
F = np.zeros(3)

# Accumulate elements of X to F based on I
np.add.at(F, I, X)

print("Vector X:", X)
print("Index list I:", I)
print("Accumulated array F:", F)

Vector X: [1 2 3 4 5]
Index list I: [0 1 2 1 0]
Accumulated array F: [6. 6. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [22]:
# Create a random (w, h, 3) image of dtype ubyte
w, h = 256, 256
image = np.random.randint(0, 256, size=(w, h, 3), dtype=np.uint8)

# Reshape the image to a 2D array where each row is a color
colors = image.reshape(-1, 3)

# Use np.unique to find unique rows (colors)
unique_colors = np.unique(colors, axis=0)

# Compute the number of unique colors
num_unique_colors = len(unique_colors)

print("Number of unique colors:", num_unique_colors)

Number of unique colors: 65411


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [24]:
import numpy as np

# Create a sample 4D array with random values
# The shape of the array is (3, 4, 5, 6)
array_4d = np.random.random((3, 4, 5, 6))

# Sum over the last two axes (-2 and -1)
# This means summing over the 5 and 6 dimensions for each element in the 3 and 4 dimensions
sum_over_last_two_axes = np.sum(array_4d, axis=(-2, -1))

# Print the shape of the original 4D array
print("Original 4D array shape:", array_4d.shape)

# Print the shape of the resulting array after summing over the last two axes
# The resulting shape should be (3, 4) because the last two dimensions are summed
print("Sum over the last two axes shape:", sum_over_last_two_axes.shape)

# Print the resulting array after summing over the last two axes
print("Sum over the last two axes:\n", sum_over_last_two_axes)

Original 4D array shape: (3, 4, 5, 6)
Sum over the last two axes shape: (3, 4)
Sum over the last two axes:
 [[14.70588375 16.76235321 14.94972608 19.27465993]
 [11.76240432 15.00672972 17.13746828 17.51351214]
 [17.4255525  17.02954103 15.6711339  16.45688595]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [26]:
# Given one-dimensional vector D
D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Vector S of the same size describing subset indices
S = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

# Compute the means of subsets of D using S
means = [D[S == i].mean() for i in np.unique(S)]

print("Vector D:", D)
print("Subset indices S:", S)
print("Means of subsets:", means)

Vector D: [ 1  2  3  4  5  6  7  8  9 10]
Subset indices S: [0 1 0 1 0 1 0 1 0 1]
Means of subsets: [np.float64(5.0), np.float64(6.0)]


#### 69. How to get the diagonal of a dot product? (★★★)

In [27]:
# Given two matrices
A = np.random.random((5, 5))
B = np.random.random((5, 5))

# Compute the diagonal of the dot product
diagonal = np.einsum('ij,ji->i', A, B)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Diagonal of the dot product:\n", diagonal)

Matrix A:
 [[0.83623299 0.02188149 0.25657858 0.57683848 0.85788404]
 [0.03976045 0.13747303 0.70021754 0.55464677 0.50086091]
 [0.53426296 0.58097539 0.84448542 0.68330683 0.65435321]
 [0.87889143 0.70493323 0.18304914 0.70816952 0.72487842]
 [0.61140285 0.9403738  0.1303034  0.57260106 0.56783822]]
Matrix B:
 [[0.17388925 0.14724772 0.17590883 0.19341919 0.99525115]
 [0.48386321 0.33328577 0.3899106  0.1314985  0.40774729]
 [0.66820928 0.25227002 0.05399946 0.12003797 0.46346215]
 [0.15047914 0.68700268 0.07770922 0.94543936 0.98038752]
 [0.89054049 0.85418939 0.02007554 0.80570196 0.72419244]]
Diagonal of the dot product:
 [1.1782304  1.03719022 0.43234753 1.53823228 2.02492004]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [29]:
# Given vector
original_vector = np.array([1, 2, 3, 4, 5])

# Create a new vector with zeros interleaved
new_vector = np.zeros(len(original_vector) * 4 - 3, dtype=original_vector.dtype)
new_vector[::4] = original_vector

print("Original vector:", original_vector)
print("New vector with interleaved zeros:", new_vector)

Original vector: [1 2 3 4 5]
New vector with interleaved zeros: [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


Save and commit your work

In [25]:
import jovian

ModuleNotFoundError: No module named 'jovian'

In [17]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [31]:
# Given arrays
array_3d = np.random.random((2, 2, 2))
array_2d = np.random.random((2, 2))

# Multiply the 3D array by the 2D array
result = array_3d * array_2d[:, :, np.newaxis]

print("3D array:\n", array_3d)
print("2D array:\n", array_2d)
print("Result of multiplication:\n", result)

3D array:
 [[[0.67813417 0.91981212]
  [0.46338785 0.21449242]]

 [[0.13493232 0.1075408 ]
  [0.59734123 0.58972545]]]
2D array:
 [[0.47608526 0.25172798]
 [0.92078814 0.30564623]]
Result of multiplication:
 [[[0.32284968 0.43790899]
  [0.11664769 0.05399374]]

 [[0.12424408 0.0990223 ]
  [0.18257509 0.18024736]]]


#### 72. How to swap two rows of an array? (★★★)

In [32]:
# Swap the first and second rows of the array A
A[[0, 1]] = A[[1, 0]]

print("Array after swapping rows:\n", A)

Array after swapping rows:
 [[0.03976045 0.13747303 0.70021754 0.55464677 0.50086091]
 [0.83623299 0.02188149 0.25657858 0.57683848 0.85788404]
 [0.53426296 0.58097539 0.84448542 0.68330683 0.65435321]
 [0.87889143 0.70493323 0.18304914 0.70816952 0.72487842]
 [0.61140285 0.9403738  0.1303034  0.57260106 0.56783822]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [33]:
# Given set of 10 triplets describing 10 triangles
triplets = np.array([
    [0, 1, 2],
    [0, 2, 3],
    [0, 3, 4],
    [0, 4, 5],
    [0, 5, 6],
    [0, 6, 7],
    [0, 7, 8],
    [0, 8, 9],
    [0, 9, 1],
    [1, 2, 3]
])

# Create a set to store unique line segments
unique_segments = set()

# Iterate through each triplet and extract line segments
for triplet in triplets:
    for i in range(3):
        segment = tuple(sorted((triplet[i], triplet[(i + 1) % 3])))
        unique_segments.add(segment)

# Convert the set to a list for easier viewing
unique_segments = list(unique_segments)
print("Unique line segments:", unique_segments)

Unique line segments: [(np.int64(3), np.int64(4)), (np.int64(0), np.int64(2)), (np.int64(8), np.int64(9)), (np.int64(0), np.int64(5)), (np.int64(0), np.int64(8)), (np.int64(1), np.int64(3)), (np.int64(1), np.int64(9)), (np.int64(4), np.int64(5)), (np.int64(5), np.int64(6)), (np.int64(0), np.int64(1)), (np.int64(0), np.int64(7)), (np.int64(1), np.int64(2)), (np.int64(0), np.int64(4)), (np.int64(6), np.int64(7)), (np.int64(0), np.int64(3)), (np.int64(0), np.int64(9)), (np.int64(0), np.int64(6)), (np.int64(2), np.int64(3)), (np.int64(7), np.int64(8))]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [35]:
# Given array C that is a bincount
C = np.array([3, 2, 1, 4])

# Produce an array A such that np.bincount(A) == C
A = np.repeat(np.arange(len(C)), C)

print("Array C (bincount):", C)
print("Array A:", A)
print("Bincount of A:", np.bincount(A))

Array C (bincount): [3 2 1 4]
Array A: [0 0 0 1 1 2 3 3 3 3]
Bincount of A: [3 2 1 4]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [36]:
import numpy as np

# Given array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Define the window size
window_size = 3

# Create a window of ones and normalize it by dividing by the window size
# This creates a moving average window
window = np.ones(window_size) / window_size

# Compute the sliding window averages using convolution
# np.convolve performs a discrete, linear convolution of two one-dimensional sequences
# mode='valid' means the convolution product is only given for points where the signals overlap completely
sliding_averages = np.convolve(array, window, mode='valid')

print("Array:", array)
print("Sliding window averages:", sliding_averages)

Array: [ 1  2  3  4  5  6  7  8  9 10]
Sliding window averages: [2. 3. 4. 5. 6. 7. 8. 9.]


np.convolve:

This function performs a discrete, linear convolution of two one-dimensional sequences. Convolution is a mathematical operation used to combine two sequences to produce a third sequence. It is often used in signal processing and other fields to analyze the effect of one sequence on another.
mode='valid':

The mode parameter in np.convolve determines the size of the output array.
'valid' mode returns the convolution product only for points where the signals overlap completely. This means the output array will be smaller than the input array, as it excludes the boundary effects where the signals do not fully overlap.
np.ones(window_size) / window_size:

np.ones(window_size) creates an array of ones with the specified window size.
Dividing by window_size normalizes the window, creating a moving average window. This means each element in the window is equal to 1/window_size, which ensures that the sum of the window elements is 1. This is used to compute the average of the elements within the window as it slides over the input array.

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [37]:
# Given one-dimensional array Z
Z = np.array([7., 8., 9.])

# Build the two-dimensional array
rows = len(Z) - 2
result = np.array([Z[i:i+3] for i in range(rows)])

print("Original array Z:", Z)
print("Two-dimensional array:\n", result)

Original array Z: [7. 8. 9.]
Two-dimensional array:
 [[7. 8. 9.]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [38]:
# Negate a boolean array in place
bool_array = np.array([True, False, True, False])
np.logical_not(bool_array, out=bool_array)
print("Negated boolean array:", bool_array)

# Change the sign of a float array in place
float_array = np.array([1.0, -2.0, 3.0, -4.0])
np.negative(float_array, out=float_array)
print("Sign-changed float array:", float_array)

Negated boolean array: [False  True False  True]
Sign-changed float array: [-1.  2. -3.  4.]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [39]:
import numpy as np

# Define the sets of points P0 and P1 describing lines
P0 = np.array([[0, 0], [1, 1], [2, 2]])
P1 = np.array([[1, 0], [2, 1], [3, 2]])

# Define the point p
p = np.array([1, 2])

# Function to compute the distance from point p to each line segment (P0[i], P1[i])
def point_to_line_distance(P0, P1, p):
    # Vector from P0 to P1
    line_vec = P1 - P0
    # Vector from P0 to p
    p_vec = P0 - p
    # Cross product of line_vec and p_vec
    cross_prod = np.cross(line_vec, p_vec)
    # Distance from p to the line
    distance = np.abs(cross_prod) / np.linalg.norm(line_vec, axis=1)
    return distance

# Compute the distances
distances = point_to_line_distance(P0, P1, p)
print("Distances from point p to each line segment:", distances)

Distances from point p to each line segment: [2. 1. 0.]


C:\Users\chris\AppData\Local\Temp\ipykernel_13304\3057873401.py:17: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  cross_prod = np.cross(line_vec, p_vec)


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [40]:
# Define the set of points P
P = np.array([[1, 2], [2, 3], [3, 4]])

# Function to compute the distance from each point P[j] to each line segment (P0[i], P1[i])
def point_to_lines_distances(P0, P1, P):
    # Vector from P0 to P1
    line_vec = P1 - P0
    # Vector from P0 to P
    p_vec = P[:, np.newaxis, :] - P0
    # Cross product of line_vec and p_vec
    cross_prod = np.cross(line_vec, p_vec)
    # Distance from P to the line
    distances = np.abs(cross_prod) / np.linalg.norm(line_vec, axis=1)
    return distances

# Compute the distances
distances = point_to_lines_distances(P0, P1, P)
print("Distances from each point P[j] to each line segment (P0[i], P1[i]):\n", distances)

Distances from each point P[j] to each line segment (P0[i], P1[i]):
 [[2. 1. 0.]
 [3. 2. 1.]
 [4. 3. 2.]]


C:\Users\chris\AppData\Local\Temp\ipykernel_13304\828435550.py:11: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  cross_prod = np.cross(line_vec, p_vec)


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [42]:
def extract_subpart(array, center, shape, fill_value=0):
    # Calculate the start and end indices for each dimension
    start_indices = [max(0, c - s // 2) for c, s in zip(center, shape)]
    end_indices = [min(d, c + (s + 1) // 2) for c, s, d in zip(center, shape, array.shape)]
    
    # Create an empty array with the desired shape and fill it with the fill_value
    subpart = np.full(shape, fill_value, dtype=array.dtype)
    
    # Calculate the slices for the original array and the subpart
    slices_original = tuple(slice(start, end) for start, end in zip(start_indices, end_indices))
    slices_subpart = tuple(slice(max(0, -c + s // 2), min(s, d - c + s // 2)) for s, c, d in zip(shape, center, array.shape))
    
    # Copy the relevant part of the original array to the subpart
    subpart[slices_subpart] = array[slices_original]
    
    return subpart

# Example usage
array = np.random.random((5, 5))
center = (2, 2)
shape = (3, 3)
fill_value = 0

subpart = extract_subpart(array, center, shape, fill_value)
print("Original array:\n", array)
print("Extracted subpart:\n", subpart)

Original array:
 [[0.5010884  0.72638882 0.87032124 0.45011043 0.73738685]
 [0.49566301 0.10889952 0.37085193 0.79387841 0.51944098]
 [0.55944361 0.21868145 0.46745472 0.68604843 0.42795889]
 [0.63512098 0.71463781 0.1744911  0.01589344 0.537649  ]
 [0.81558049 0.68776471 0.90817525 0.61980683 0.40562844]]
Extracted subpart:
 [[0.10889952 0.37085193 0.79387841]
 [0.21868145 0.46745472 0.68604843]
 [0.71463781 0.1744911  0.01589344]]


Save and commit your work.

In [18]:
import jovian

In [19]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [43]:
# Given array Z
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# Generate the array R using a sliding window approach
R = np.array([Z[i:i+4] for i in range(len(Z) - 3)])

print("Array Z:", Z)
print("Generated array R:\n", R)

Array Z: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Generated array R:
 [[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [44]:
import numpy as np

# Given matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

print("Matrix:\n", matrix)
print("Rank of the matrix:", rank)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank of the matrix: 2


#### 83. How to find the most frequent value in an array?

In [45]:
# Given array
array = np.array([0, 0, 0, 1, 1, 2, 3, 3, 3, 3])

# Find the most frequent value
most_frequent_value = np.bincount(array).argmax()

print("Most frequent value in the array:", most_frequent_value)

Most frequent value in the array: 3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [46]:
# Create a random 10x10 matrix
matrix_10x10 = np.random.random((10, 10))
print("Original 10x10 matrix:\n", matrix_10x10)

# Extract all contiguous 3x3 blocks
blocks = np.lib.stride_tricks.sliding_window_view(matrix_10x10, (3, 3))

# Reshape the blocks to a 2D array where each row is a 3x3 block
blocks_reshaped = blocks.reshape(-1, 3, 3)

print("All contiguous 3x3 blocks:\n", blocks_reshaped)

Original 10x10 matrix:
 [[3.73013358e-01 8.89471117e-01 4.32297390e-02 5.72722424e-01
  9.54176219e-01 9.73721942e-01 9.17249981e-01 4.01789875e-01
  5.89376421e-01 8.08005005e-01]
 [3.23860338e-01 7.58272547e-01 5.24093740e-01 7.66341083e-02
  9.24764800e-01 3.32173238e-01 4.24987962e-01 7.40910835e-01
  9.09119131e-01 9.36780214e-01]
 [5.08507971e-01 1.46893433e-01 9.13528006e-01 1.85185871e-01
  6.34233033e-01 5.31796017e-01 1.95642201e-01 6.41653186e-01
  4.83063549e-01 9.20946843e-01]
 [9.04766074e-01 1.27502475e-01 3.88932155e-01 5.28663455e-01
  9.40818340e-01 4.47373360e-01 8.69940083e-01 5.37745824e-01
  4.53646227e-01 4.61070787e-01]
 [1.49771919e-01 7.38151359e-01 4.58461977e-01 5.64408976e-01
  4.95183224e-01 6.45549922e-02 1.44181979e-01 9.03535822e-01
  8.76664052e-02 1.90676874e-01]
 [1.92373398e-01 1.22442978e-01 8.40807992e-01 4.96552907e-01
  6.09436067e-01 8.50643885e-01 8.39247910e-01 8.00243682e-01
  1.64616323e-01 6.83305033e-01]
 [4.44544312e-01 6.05981842e-01 9.

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [47]:
import numpy as np

class SymmetricArray(np.ndarray):
    def __new__(cls, shape, dtype=float, buffer=None, offset=0,
                strides=None, order=None):
        obj = super(SymmetricArray, cls).__new__(cls, shape, dtype, buffer, offset, strides, order)
        return obj

    def __setitem__(self, index, value):
        i, j = index
        super(SymmetricArray, self).__setitem__((i, j), value)
        super(SymmetricArray, self).__setitem__((j, i), value)

# Example usage
shape = (5, 5)
Z = SymmetricArray(shape)
Z[1, 2] = 10
print(Z)

[[7.74860419e-304 7.74860419e-304 7.74860419e-304 7.74860419e-304
  7.74860419e-304]
 [7.74860419e-304 7.74860419e-304 1.00000000e+001 7.74860419e-304
  7.74860419e-304]
 [7.74860419e-304 1.00000000e+001 7.74860419e-304 7.74860419e-304
  7.74860419e-304]
 [7.74860419e-304 7.74860419e-304 7.74860419e-304 7.74860419e-304
  7.74860419e-304]
 [7.74860419e-304 7.74860419e-304 7.74860419e-304 7.74860419e-304
  7.74860419e-304]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [48]:
# Define the set of p matrices with shape (n, n)
p = 3
n = 2
matrices = np.random.random((p, n, n))

# Define the set of p vectors with shape (n, 1)
vectors = np.random.random((p, n, 1))

# Compute the sum of the p matrix products
result = np.einsum('pij,pjk->ik', matrices, vectors).sum(axis=0)

print("Matrices:\n", matrices)
print("Vectors:\n", vectors)
print("Result of the sum of the p matrix products:\n", result)

Matrices:
 [[[0.77114328 0.01084482]
  [0.22335682 0.89276227]]

 [[0.61357774 0.2450837 ]
  [0.67476291 0.30154172]]

 [[0.93632799 0.58274352]
  [0.84265568 0.46432113]]]
Vectors:
 [[[0.83336229]
  [0.13309393]]

 [[0.13157706]
  [0.84420795]]

 [[0.5012213 ]
  [0.41230591]]]
Result of the sum of the p matrix products:
 [2.90340056]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [49]:
# Create a random 16x16 array
array_16x16 = np.random.random((16, 16))

# Reshape the array to (4, 4, 4, 4) and sum over the appropriate axes
block_sum = array_16x16.reshape(4, 4, 4, 4).sum(axis=(2, 3))

print("Original 16x16 array:\n", array_16x16)
print("Block-sum (4x4):\n", block_sum)

Original 16x16 array:
 [[0.49242922 0.77364311 0.21002834 0.7645766  0.70072584 0.45528513
  0.97641353 0.87255224 0.97282538 0.87168177 0.36387261 0.36895562
  0.45626449 0.97039002 0.1142202  0.53174635]
 [0.96997759 0.27725956 0.45140494 0.4973471  0.81468295 0.05392628
  0.58151925 0.70357118 0.79373859 0.97670785 0.87969143 0.71668889
  0.64005024 0.45433991 0.51557086 0.73717305]
 [0.69625808 0.15176328 0.39159343 0.62213667 0.67177692 0.39109574
  0.199037   0.67310462 0.49451721 0.98229737 0.80423907 0.71537447
  0.20797787 0.11292618 0.85900086 0.38058361]
 [0.60081419 0.51066131 0.61242077 0.75706613 0.34337066 0.75182362
  0.33438997 0.90536827 0.33323499 0.21101874 0.38651837 0.40344643
  0.99472184 0.80410473 0.10054189 0.42550871]
 [0.13389821 0.88247527 0.75904214 0.02078707 0.42911837 0.93163313
  0.96466532 0.63880712 0.04706367 0.72252034 0.71815524 0.55108521
  0.65312318 0.71220487 0.82550835 0.98722473]
 [0.91800558 0.34891541 0.92346242 0.89435677 0.17152936 0.880

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [50]:
import numpy as np

def game_of_life_step(grid):
    # Create a padded grid to handle edge cases
    padded_grid = np.pad(grid, pad_width=1, mode='constant', constant_values=0)
    
    # Initialize the next state grid
    next_grid = np.zeros_like(grid)
    
    # Iterate over each cell in the grid
    for i in range(1, padded_grid.shape[0] - 1):
        for j in range(1, padded_grid.shape[1] - 1):
            # Count the number of live neighbors
            live_neighbors = np.sum(padded_grid[i-1:i+2, j-1:j+2]) - padded_grid[i, j]
            
            # Apply the rules of the Game of Life
            if padded_grid[i, j] == 1:
                if live_neighbors < 2 or live_neighbors > 3:
                    next_grid[i-1, j-1] = 0
                else:
                    next_grid[i-1, j-1] = 1
            else:
                if live_neighbors == 3:
                    next_grid[i-1, j-1] = 1
    
    return next_grid

# Initialize the grid with random values (0 or 1)
grid_size = (10, 10)
grid = np.random.randint(2, size=grid_size)

# Print the initial state of the grid
print("Initial grid:")
print(grid)

# Simulate the Game of Life for a number of steps
num_steps = 5
for step in range(num_steps):
    grid = game_of_life_step(grid)
    print(f"Grid after step {step + 1}:")
    print(grid)

Initial grid:
[[0 1 1 1 0 0 1 1 1 0]
 [1 1 1 0 1 1 1 0 0 0]
 [1 1 1 1 1 0 1 0 0 1]
 [0 0 1 0 1 0 0 1 0 1]
 [1 1 0 0 1 1 0 1 1 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 1]
 [1 1 0 1 1 1 0 1 0 0]
 [1 0 1 1 1 1 1 0 1 0]
 [0 1 1 1 1 1 1 1 0 1]]
Grid after step 1:
[[1 0 0 1 1 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 1 1 1 0]
 [0 0 0 0 0 0 0 1 0 1]
 [1 1 0 1 1 1 1 1 1 0]
 [1 0 0 0 1 0 0 0 1 0]
 [1 0 1 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 1 0]
 [1 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 1 1 0]]
Grid after step 2:
[[0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 1 0 0 1]
 [1 1 0 0 1 0 0 0 0 1]
 [1 1 0 1 1 1 1 0 0 1]
 [1 0 0 0 0 0 1 0 1 0]
 [1 0 0 1 0 0 0 1 1 0]
 [1 0 0 0 0 0 0 1 1 0]
 [1 1 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1 1 0]]
Grid after step 3:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 0]
 [0 0 0 0 0 1 0 0 1 1]
 [1 1 1 1 1 0 1 0 1 1]
 [0 0 1 1 1 0 1 1 1 1]
 [1 0 1 1 0 0 1 0 1 1]
 [1 1 0 0 0 0 1 0 0 1]
 [1 0 0 0 0 0 0 1 0 1]
 [1 1 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 1 0]]
Grid 

#### 89. How to get the n largest values of an array (★★★)

In [ ]:
import numpy as np

# Given array
array = np.random.random(100)

# Number of largest values to get
n = 5

# Get the n largest values
n_largest_values = np.partition(array, -n)[-n:]

# Sort the n largest values in descending order
n_largest_values = np.sort(n_largest_values)[::-1]

print("Array:", array)
print(f"{n} largest values:", n_largest_values)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [51]:
import numpy as np
import itertools

# Given vectors
vectors = [np.array([1, 2, 3]), np.array([4, 5]), np.array([6, 7])]

# Build the Cartesian product
cartesian_product = np.array(list(itertools.product(*vectors)))

print("Vectors:", vectors)
print("Cartesian product:\n", cartesian_product)

Vectors: [array([1, 2, 3]), array([4, 5]), array([6, 7])]
Cartesian product:
 [[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


Save and commit your work

In [20]:
import jovian

In [21]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 91. How to create a record array from a regular array? (★★★)

In [52]:
# Given regular array
regular_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Define the data types for the record array
dtype = [('col1', 'i4'), ('col2', 'i4'), ('col3', 'i4')]

# Create the record array from the regular array
record_array = np.core.records.fromarrays(regular_array.T, dtype=dtype)

print("Regular array:\n", regular_array)
print("Record array:\n", record_array)

Regular array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Record array:
 [(1, 2, 3) (4, 5, 6) (7, 8, 9)]


C:\Users\chris\AppData\Local\Temp\ipykernel_13304\1811569410.py:8: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  record_array = np.core.records.fromarrays(regular_array.T, dtype=dtype)


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [53]:
# Given large vector Z
Z = np.random.rand(1000000)

# Method 1: Using the ** operator
Z_power_3_method1 = Z ** 3

# Method 2: Using np.power function
Z_power_3_method2 = np.power(Z, 3)

# Method 3: Using element-wise multiplication
Z_power_3_method3 = Z * Z * Z

# Verify that all methods give the same result
print(np.allclose(Z_power_3_method1, Z_power_3_method2))
print(np.allclose(Z_power_3_method1, Z_power_3_method3))

True
True


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [55]:
# Given arrays A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [1, 3, 2],
              [4, 6, 5],
              [7, 9, 8],
              [1, 4, 7],
              [2, 5, 8]])

B = np.array([[1, 2],
              [4, 5]])

# Function to find rows of A that contain elements of each row of B
def find_matching_rows(A, B):
    matching_rows = []
    for row in A:
        if all(np.isin(b_row, row).all() for b_row in B):
            matching_rows.append(row)
    return np.array(matching_rows)

# Find the matching rows
matching_rows = find_matching_rows(A, B)

print("Array A:\n", A)
print("Array B:\n", B)
print("Matching rows:\n", matching_rows)

Array A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 3 2]
 [4 6 5]
 [7 9 8]
 [1 4 7]
 [2 5 8]]
Array B:
 [[1 2]
 [4 5]]
Matching rows:
 []


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [56]:
# Create a sample 10x3 matrix
matrix_10x3 = np.random.randint(0, 5, (10, 3))
print("Original 10x3 matrix:\n", matrix_10x3)

# Extract rows with unequal values
rows_with_unequal_values = matrix_10x3[np.apply_along_axis(lambda x: len(np.unique(x)) == len(x), 1, matrix_10x3)]

print("Rows with unequal values:\n", rows_with_unequal_values)

Original 10x3 matrix:
 [[3 0 3]
 [2 2 0]
 [2 4 3]
 [4 1 3]
 [4 0 1]
 [0 1 1]
 [2 0 3]
 [3 1 4]
 [1 1 2]
 [1 0 4]]
Rows with unequal values:
 [[2 4 3]
 [4 1 3]
 [4 0 1]
 [2 0 3]
 [3 1 4]
 [1 0 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [57]:
# Given vector of integers
vector_of_ints = np.array([1, 2, 3, 4, 5])

# Convert the vector of integers to a binary matrix representation
# First, convert the integers to unsigned 8-bit integers
vector_of_uint8 = vector_of_ints.astype(np.uint8)

# Use np.unpackbits to get the binary representation
binary_matrix = np.unpackbits(vector_of_uint8[:, np.newaxis], axis=1)

print("Vector of integers:", vector_of_ints)
print("Binary matrix representation:\n", binary_matrix)

Vector of integers: [1 2 3 4 5]
Binary matrix representation:
 [[0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [58]:
# Given two-dimensional array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [1, 2, 3],
                     [7, 8, 9]])

# Extract unique rows
unique_rows = np.unique(array_2d, axis=0)

print("Original array:\n", array_2d)
print("Unique rows:\n", unique_rows)

Original array:
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]]
Unique rows:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [59]:
# Given vectors A and B
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Einsum equivalent of inner product
inner_product = np.einsum('i,i->', A, B)
print("Inner product:", inner_product)

# Einsum equivalent of outer product
outer_product = np.einsum('i,j->ij', A, B)
print("Outer product:\n", outer_product)

# Einsum equivalent of sum
sum_result = np.einsum('i->', A)
print("Sum of A:", sum_result)

# Einsum equivalent of element-wise multiplication
elementwise_mul = np.einsum('i,i->i', A, B)
print("Element-wise multiplication:", elementwise_mul)

Inner product: 32
Outer product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Sum of A: 6
Element-wise multiplication: [ 4 10 18]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [60]:
import numpy as np

# Given path described by two vectors X and Y
X = np.array([0, 1, 2, 3, 4])
Y = np.array([0, 1, 0, 1, 0])

# Number of equidistant samples
num_samples = 10

# Compute the cumulative distance along the path
distances = np.sqrt(np.diff(X)**2 + np.diff(Y)**2)
cumulative_distances = np.insert(np.cumsum(distances), 0, 0)

# Generate equidistant sample points
sample_distances = np.linspace(0, cumulative_distances[-1], num_samples)

# Interpolate the X and Y coordinates at the sample points
X_samples = np.interp(sample_distances, cumulative_distances, X)
Y_samples = np.interp(sample_distances, cumulative_distances, Y)

print("Equidistant samples (X):", X_samples)
print("Equidistant samples (Y):", Y_samples)

Equidistant samples (X): [0.         0.44444444 0.88888889 1.33333333 1.77777778 2.22222222
 2.66666667 3.11111111 3.55555556 4.        ]
Equidistant samples (Y): [0.         0.44444444 0.88888889 0.66666667 0.22222222 0.22222222
 0.66666667 0.88888889 0.44444444 0.        ]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [61]:
# Given integer n
n = 5

# Given 2D array X
X = np.array([[1, 2, 2],
              [2, 2, 1],
              [1.5, 2.5, 1],
              [3, 1, 1],
              [2, 3, 0]])

# Function to filter rows that are draws from a multinomial distribution with n degrees
def filter_multinomial_rows(X, n):
    return np.array([row for row in X if np.all(row == np.floor(row)) and np.sum(row) == n])

# Filter the rows
filtered_rows = filter_multinomial_rows(X, n)

print("Filtered rows:\n", filtered_rows)

Filtered rows:
 [[1. 2. 2.]
 [2. 2. 1.]
 [3. 1. 1.]
 [2. 3. 0.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [62]:
import numpy as np

# Given 1D array X
X = np.random.rand(1000)

# Number of bootstrap samples
N = 10000

# Function to compute bootstrap confidence intervals
def bootstrap_confidence_interval(data, num_samples, confidence_level=0.95):
    # Generate bootstrap samples and compute their means
    bootstrap_means = np.array([np.mean(np.random.choice(data, size=len(data), replace=True)) for _ in range(num_samples)])
    
    # Compute the percentiles for the confidence interval
    lower_percentile = (1 - confidence_level) / 2 * 100
    upper_percentile = (1 + confidence_level) / 2 * 100
    confidence_interval = np.percentile(bootstrap_means, [lower_percentile, upper_percentile])
    
    return confidence_interval

# Compute the 95% confidence interval for the mean of X
confidence_interval = bootstrap_confidence_interval(X, N)
print("95% confidence interval for the mean:", confidence_interval)

95% confidence interval for the mean: [0.49892699 0.53461795]


Save and commit your work

In [22]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Congratulations on completing the 100 exercises, well done!

#### What to do next?

- Share your completed notebook on Facebook, LinkedIn or Twitter and challenge your friends.
- Share your solutions and help others on the forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561
- Check out our course on "Data Analysis with Python: Zero to Pandas" - https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas
- Star this repository to show your appreciation for the original author of this notebook: https://github.com/rougier/numpy-100